version: "3"
services:
  reverseproxy:
    build:
      context: udagram-reverse-proxy
    image: finfalter/udagram-reverse-proxy
    ports:
    - 8080:8080
    restart: always
    depends_on:
      - udagram-user
      - udagram-feed
  udagram-user:
    build:
      context: udagram-user
    image: finfalter/udagram-user
    volumes:
      - $HOME/.aws/credentials:/root/.aws/credentials:ro
    environment:
      POSTGRES_USERNAME : $POSTGRES_USERNAME
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_DB: $POSTGRES_DB
      POSTGRES_HOST: $POSTGRES_HOST
      AWS_REGION: $AWS_REGION
      AWS_PROFILE: $AWS_PROFILE
      AWS_BUCKET: $AWS_BUCKET
      JWT_SECRET: $JWT_SECRET
      URL: "http://localhost:8100"
  udagram-feed:
    build:
      context: udagram-feed
    image: finfalter/udagran-feed
    volumes:
      - $HOME/.aws/credentials:/root/.aws/credentials:ro
    environment:
      POSTGRES_USERNAME : $POSTGRES_USERNAME
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_DB: $POSTGRES_DB
      POSTGRES_HOST: $POSTGRES_HOST
      AWS_REGION: $AWS_REGION
      AWS_PROFILE: $AWS_PROFILE
      AWS_BUCKET: $AWS_BUCKET
      JWT_SECRET: $JWT_SECRET
      URL: "http://localhost:8100"
  udagram-frontend:
    build:
      context: udagram-feed
    image: finfalter/udagram-frontend
    ports:
      - "8100:80"