apiVersion: apps/v1
kind: Deployment
metadata:
  name: udagram-user
  labels:
    service: udagram-user
spec:
  replicas: 1
  selector:
    matchLabels:
      service: udagram-user
  template:
    metadata:
      labels:
        service: udagram-user
    spec:
      containers:
      - name: udagram-user
        image: finfalter/udagram-user
        imagePullPolicy: Always
        envFrom:
        - configMapRef:
            name: udagram-env
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "1024Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: aws-secret
          mountPath: /usr/src/app/secret/
          readOnly: true  
      volumes:
      - name: aws-secret
        secret:
          secretName: aws-secret
      - name: env-secret
        secret:
          secretName: env-secret