apiVersion: apps/v1
kind: Deployment
metadata:
  name: udagram-user
  labels:
    service: udagram-user
spec:
  replicas: 1
  selector:
    matchLabels:
      service: udagram-user
  template:
    metadata:
      labels:
        service: udagram-user
    spec:
      containers:
      - name: udagram-user
        image: finfalter/udagram-user
        imagePullPolicy: Always
        envFrom:
        - configMapRef:
            name: udagram-env
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "1024Mi"
            cpu: "500m"
        env:
        - name: URL
          valueFrom:
            configMapKeyRef:
              name: udagram-env
              key: URL
        - name: AWS_BUCKET
          valueFrom:
            configMapKeyRef:
              name: udagram-env
              key: AWS_BUCKET
        - name: AWS_PROFILE
          valueFrom:
            configMapKeyRef:
              name: udagram-env
              key: AWS_PROFILE
        - name: AWS_REGION
          valueFrom:
            configMapKeyRef:
              name: udagram-env
              key: AWS_REGION
        - name: JWT_SECRET
          valueFrom:
            configMapKeyRef:
              name: udagram-env
              key: JWT_SECRET
        - name: POSTGRES_DB
          valueFrom:
            configMapKeyRef:
              name: udagram-env
              key: POSTGRES_DB
        - name: POSTGRES_HOST
          valueFrom:
            configMapKeyRef:
              name: udagram-env
              key: POSTGRES_HOST
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: env-secret
              key: POSTGRES_PASSWORD
        - name: POSTGRES_USERNAME
          valueFrom:
            secretKeyRef:
              name: env-secret
              key: POSTGRES_USERNAME     
        volumeMounts:
        - name: aws-secret
          mountPath: "/root/.aws/"
          readOnly: true  
      restartPolicy: Always     
      volumes:
      - name: aws-secret
        secret:
          secretName: aws-secret